### Health Check
GET localhost:4000/healthcheck

### Register User
POST localhost:4000/users
Content-Type: application/json

{
  "user": {
    "name": "Alice",
    "email": "alice@gmail.com",
    "password": "pa55word"
  }
}
